# Analysis options for Digi-Kul Student App
# This file configures the analyzer for strict code quality standards

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated_plugin_registrant.dart"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable rules that conflict with our code style
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    
    # Enable additional rules for better code quality
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    use_build_context_synchronously: true
    
    # Flutter specific rules
    use_colored_box: true
    use_decorated_box: true
    sized_box_for_whitespace: true
    avoid_unnecessary_containers: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
