name: digikul_student_app
description: "Digi-Kul Student Mobile Application - Audio-first, offline-capable educational platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core UI and Icons
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # HTTP and Networking
  dio: ^5.4.0
  http: ^1.2.1
  connectivity_plus: ^5.0.2
  
  # Real-time Communication & WebRTC
  socket_io_client: ^2.0.3+1
  flutter_webrtc: ^0.9.48
  
  # Local Storage and Offline Capability
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Navigation
  go_router: ^12.1.3
  
  # File Handling and Downloads
  url_launcher: ^6.2.6
  path: ^1.8.3
  file_picker: ^6.1.1
  open_file: ^3.3.2
  permission_handler: ^11.1.0
  
  # UI Enhancements and Loading
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0
  
  # Audio and Media
  just_audio: ^0.9.36
  audio_session: ^0.1.16
  
  # Utilities and Formatting
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.2.2
  logger: ^2.0.2+1
  
  # Image and Icon Handling
  flutter_svg: ^2.0.9
  
  # Platform Integration
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Testing
  mocktail: ^1.0.2
  integration_test:
    sdk: flutter

  # Linting and Analysis
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
